Repository exercism/problem-specifications, pull requests merged in 2019-06, with the labels that each got.

#1538 Clarify goal in the DOT DSL blurb and description
  exercises/dot-dsl/description.md
  exercises/dot-dsl/metadata.yml
Labels: correctness, documentation

#1540 [Darts] Add additional edge case
  exercises/darts/canonical-data.json
Labels: new test case idea

#1518 [RFC] Add 'optional' key to canonical-schema
  .travis.yml
  OPTIONAL-KEYS.txt
  README.md
  bin/check_optional
  canonical-schema.json
Labels: cross-track consistency
