Repository exercism/problem-specifications, pull requests merged in 2020-10, with the labels that each got.

#1683 Add scenarios to README example and describe purpose
  README.md
Labels: documentation, hacktoberfest-accepted

#1697 CI: Clean up workflow and clarify what "JS tests" are
  .github/workflows/ci.yml
Labels: CI, hacktoberfest-accepted

#1699 CI: Add codeowners
  .github/CODEOWNERS
Labels: CI

#1612 list-ops: add append case
  exercises/list-ops/canonical-data.json
Labels: hold, new test case idea

#1702 CI: Add check that reimplemented-values are valid UUIDs
  .github/workflows/ci.yml
Labels: CI

#1582 Square-Root: Add new exercise
  exercises/square-root/canonical-data.json
  exercises/square-root/description.md
  exercises/square-root/metadata.yml
Labels: new exercise idea

#1711 CI: Add workflow_dispatch as manual trigger
  .github/workflows/ci.yml
Labels: CI

#1722 Add workflow recommendations and templates
  README.md
  workflows/README.md
  workflows/ci.yml
  workflows/configlet.yml
  workflows/pr.ci.yml
Labels: CI, documentation

#1712 CI: Ensure immutability of test cases
  .github/workflow-tests/immutability-check/canonical-data-changed-scenarios-after.json
  .github/workflow-tests/immutability-check/canonical-data-changed-scenarios-before.json
  .github/workflow-tests/immutability-check/canonical-data-deleted-case.json
  .github/workflow-tests/immutability-check/canonical-data-mutated-and-deleted.json
  .github/workflow-tests/immutability-check/canonical-data-mutated.json
  .github/workflow-tests/immutability-check/canonical-data-new-test.json
  .github/workflow-tests/immutability-check/canonical-data.json
  .github/workflows/ci.yml
  bin/check-immutability.py
Labels: CI, hacktoberfest-accepted
