Repository exercism/problem-specifications, pull requests merged in 2021-12, with the labels that each got.

#1741 flatten-array: add intermediate TDD-supporting tests
  exercises/flatten-array/canonical-data.json
Labels: new test case idea

#1756 protein-translation: input validation test cases
  exercises/protein-translation/canonical-data.json
Labels: new test case idea

#1841 Fix links in CONTRIBUTING.md.
  CONTRIBUTING.md
Labels: x:action/fix, x:type/docs

#1899 Atbash Cipher: Refine the exercise description
  exercises/atbash-cipher/description.md
Labels: x:size/small

#1901 Markdown style for Exercism
  CONTRIBUTING.md
Labels: documentation, cross-track consistency, x:knowledge/none, x:status/claimed, x:type/content, x:type/docs, x:size/tiny
