Repository exercism/problem-specifications, pull requests merged in 2022-01, with the labels that each got.

#1904 isbn-verifier: Distinguish two different invalid character tests
  exercises/isbn-verifier/canonical-data.json
Labels: x:size/small

#1911 Affine markdown style guide applied
  exercises/affine-cipher/description.md
Labels: documentation, x:knowledge/none, x:status/claimed, x:type/content, x:type/docs, x:size/tiny

#1895 Add markdown lint to CI workflow
  .github/workflows/ci.yml
  .markdownlint.jsonc
  CONTRIBUTING.md
  STYLE-GUIDE.md
  exercises/book-store/description.md
  exercises/pov/description.md
  exercises/queen-attack/description.md
  exercises/scale-generator/description.md
Labels: x:action/create, x:knowledge/elementary, x:type/ci, x:size/small

#1918 Deprecate exercise "accumulate"
  exercises/accumulate/.deprecated
Labels: x:size/small
