Repository exercism/problem-specifications, pull requests merged in 2023-06, with the labels that each got.

#2145 Add link checking for markdown in CI
  .github/workflows/ci.yml
  .lycheeignore
Labels: CI, x:action/create, x:knowledge/elementary, x:type/ci, x:size/small, x:rep/small

#2288 lychee: do not link check (exercises/house) [papyr.com; it times out from GitHub actions
  .lycheeignore
Labels: x:action/fix, x:type/coding, x:size/small, x:rep/small

#2287 Create canonical data for ledger, lifted from the Python tests
  exercises/ledger/canonical-data.json
Labels: x:action/create, x:module/practice-exercise, x:type/coding

#2295 High Score: drop implementation details from the problem spec
  exercises/high-scores/canonical-data.json
Labels: x:type/docs, x:size/small, x:rep/small
