Repository exercism/problem-specifications, pull requests merged in 2024-06, with the labels that each got.

#2452 Fix typo in pig-latin instructions
  exercises/pig-latin/instructions.md
Labels: x:rep/tiny

#2457 wikipedia to Wikipedia
  exercises/bank-account/instructions.md
  exercises/go-counting/description.md
  exercises/nucleotide-codons/description.md
  exercises/poker/description.md
  exercises/yacht/metadata.toml
Labels: x:rep/tiny

#2459 Banish the smokers from the zebra puzzle
  exercises/zebra-puzzle/instructions.md
  exercises/zebra-puzzle/introduction.md
Labels: x:rep/small

#2460 Add some punctuation
  exercises/affine-cipher/description.md
Labels: x:type/docs, x:size/small, x:rep/small
